name: build pages
'on':
  push:
    branches:
      - master
env:
  SITE_HOST: githubpages
jobs:
  environment:
    name: github-pages
    url: ${{steps.deployment.outputs.page_url}}
  build-pages:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.head_commit.message, '[deploy]') || (!contains(github.event.head_commit.message, '[preview]') && !contains(github.event.head_commit.message, '[test]')) }}"
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v2

      - uses: jiro4989/setup-nim-action@v1
      
      - name: install builder dependencies
        run: nimble install -y
      
      - name: run builder
        run: nimble runBuilder

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
